name: project_info
trigger: SessionStart
actions:
  - type: message
    text: "Loaded from repo-level hooks"
  - type: command
    command: "git --no-pager log -1 --oneline"
    inject_as: "last_commit"
