//! Demo screen showing generative slot components

use crate::ui::r#gen::{GenContainer, GenText, GenerativeContext, GenerativeProvider};
use freya::prelude::*;

/// Gen components demo screen - entry point
pub fn gen_demo_screen() -> Element {
    Element::from(GenDemoScreen)
}

#[derive(Clone, Copy, PartialEq)]
pub struct GenDemoScreen;

impl Component for GenDemoScreen {
    fn render(&self) -> impl IntoElement {
        // Create generative context with some pre-loaded values
        let gen_ctx = use_hook(|| {
            let ctx = GenerativeContext::new();
            ctx.set_text("demo_title".to_string(), "AI-Generated Title".to_string());
            ctx.set_color("demo_title".to_string(), (33, 150, 243)); // Blue
            ctx.set_text(
                "demo_body".to_string(),
                "This text was generated by the LLM!".to_string(),
            );
            ctx.set_color("demo_container".to_string(), (200, 230, 201)); // Green 100
            ctx
        });

        GenerativeProvider::new(gen_ctx.clone()).child(
            rect()
                .width(Size::fill())
                .height(Size::fill())
                .vertical()
                .padding(Gaps::new_all(24.0))
                .background((18, 18, 18))
                .spacing(16.0)
                .child(
                    // Header
                    label()
                        .text("Generative Slot Components Demo")
                        .font_size(28.0)
                        .color((255, 255, 255)),
                )
                .child(
                    // Description
                    label()
                        .text("Components use generated values when available, fall back to props otherwise.")
                        .font_size(14.0)
                        .color((200, 200, 200)),
                )
                .child(
                    // Section 1: GenText with slot (uses generated values)
                    rect()
                        .width(Size::fill())
                        .vertical()
                        .spacing(8.0)
                        .child(
                            label()
                                .text("Section 1: GenText with slot_id (uses generated text/color)")
                                .font_size(12.0)
                                .color((150, 150, 150)),
                        )
                        .child(
                            GenText::new()
                                .text("Fallback Title")
                                .font_size(28.0)
                                .color((255, 255, 255))
                                .slot_id("demo_title"),
                        ),
                )
                .child(
                    // Section 2: GenText without slot (uses fallback)
                    rect()
                        .width(Size::fill())
                        .vertical()
                        .spacing(8.0)
                        .child(
                            label()
                                .text("Section 2: GenText without slot_id (uses fallback props)")
                                .font_size(12.0)
                                .color((150, 150, 150)),
                        )
                        .child(
                            GenText::new()
                                .text("This uses fallback props (no slot)")
                                .font_size(14.0)
                                .color((150, 150, 150)),
                        ),
                )
                .child(
                    // Section 3: GenContainer with slot
                    rect()
                        .width(Size::fill())
                        .vertical()
                        .spacing(8.0)
                        .child(
                            label()
                                .text("Section 3: GenContainer with slot_id (uses generated background)")
                                .font_size(12.0)
                                .color((150, 150, 150)),
                        )
                        .child(
                            GenContainer::new()
                                .width(Size::fill())
                                .background((255, 255, 255))
                                .corner_radius(8.0)
                                .padding(16.0)
                                .slot_id("demo_container")
                                .child(
                                    GenText::new()
                                        .text("Fallback body text")
                                        .font_size(14.0)
                                        .color((0, 0, 0))
                                        .slot_id("demo_body"),
                                ),
                        ),
                )
                .child(
                    // Section 4: GenContainer without slot (fallback styling)
                    rect()
                        .width(Size::fill())
                        .vertical()
                        .spacing(8.0)
                        .child(
                            label()
                                .text("Section 4: GenContainer without slot_id (uses fallback gray background)")
                                .font_size(12.0)
                                .color((150, 150, 150)),
                        )
                        .child(
                            GenContainer::new()
                                .width(Size::fill())
                                .background((66, 66, 66))
                                .corner_radius(8.0)
                                .padding(16.0)
                                .child(
                                    GenText::new()
                                        .text("No slot - uses fallback gray background")
                                        .font_size(14.0)
                                        .color((255, 255, 255)),
                                ),
                        ),
                ),
        )
    }
}
