// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Embedded BAML source files.

use std::collections::HashMap;
use std::sync::OnceLock;

static FILE_MAP: OnceLock<HashMap<String, String>> = OnceLock::new();

/// Get the embedded BAML source files.
pub fn get_baml_files() -> &'static HashMap<String, String> {
    FILE_MAP.get_or_init(|| {
        let mut m = HashMap::new();

        m.insert("chat.baml".to_string(), "/// A single turn in a multi-turn conversation.\nclass ChatMessage {\n    role string @description(\"'user' or 'assistant'\")\n    content string @description(\"Text content of the message\")\n}\n\n/// Perform a multi-turn chat inference.\n///\n/// `system` is injected as the system prompt.\n/// `messages` is the full conversation history up to and including the\n/// current user turn.\nfunction Chat(system: string, messages: ChatMessage[]) -> string {\n    client DefaultClient\n    prompt #\"\n        {{ _.role(\"system\") }}\n        {{ system }}\n\n        {% for msg in messages %}\n        {{ _.role(msg.role) }}\n        {{ msg.content }}\n        {% endfor %}\n    \"#\n}\n".to_string());

        m.insert("clients.baml".to_string(), "client<llm> Anthropic {\n    provider anthropic\n    retry_policy Retry\n    options {\n        model \"claude-sonnet-4-6\"\n        api_key env.ANTHROPIC_API_KEY\n        max_tokens 8096\n    }\n}\n\nclient<llm> OpenAI {\n    provider openai\n    retry_policy Retry\n    options {\n        model \"gpt-4o\"\n        api_key env.OPENAI_API_KEY\n    }\n}\n\nclient<llm> Ollama {\n    provider openai-generic\n    options {\n        base_url \"http://localhost:11434/v1\"\n        model \"llama3.2\"\n    }\n}\n\nclient<llm> DefaultClient {\n    provider fallback\n    options {\n        strategy [Anthropic, OpenAI]\n    }\n}\n\nretry_policy Retry {\n    max_retries 2\n    strategy {\n        type exponential_backoff\n        delay_ms 500\n        multiplier 2\n        max_delay_ms 10000\n    }\n}\n".to_string());

        m.insert("generators.baml".to_string(), "generator target {\n    output_type \"rust\"\n    output_dir \"../src\"\n    version \"0.219.0\"\n    default_client_mode async\n}\n".to_string());

        m
    })
}
