// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{BamlDecode, BamlEncode};

/// A single turn in a multi-turn conversation.

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ChatMessage {
    pub role: String,

    pub content: String,
}

impl AsRef<ChatMessage> for ChatMessage {
    fn as_ref(&self) -> &ChatMessage {
        self
    }
}
