// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{
    __internal::serde::{Deserialize, Serialize},
    BamlDecode, BamlEncode,
};

/// A single turn in a multi-turn conversation.

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ChatMessage {
    pub role: String,
    pub content: String,
}

impl ::std::convert::AsRef<ChatMessage> for ChatMessage {
    fn as_ref(&self) -> &ChatMessage {
        self
    }
}

/// A single tool invocation requested by the model.

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ToolCall {
    pub name: String,
    pub arguments: String,
    pub id: String,
}

impl ::std::convert::AsRef<ToolCall> for ToolCall {
    fn as_ref(&self) -> &ToolCall {
        self
    }
}

/// Describes a tool the model may call. `input_schema` is the tool's JSON
/// schema serialized as a string (kept as a string to avoid modeling
/// arbitrary JSON Schema shapes in BAML).

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ToolDefinition {
    pub name: String,
    pub description: String,
    pub input_schema: String,
}

impl ::std::convert::AsRef<ToolDefinition> for ToolDefinition {
    fn as_ref(&self) -> &ToolDefinition {
        self
    }
}
