// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{BamlDecode, BamlEncode};

/// A single turn in a multi-turn conversation.

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ChatMessage {
    pub role: String,

    pub content: String,
}

impl AsRef<ChatMessage> for ChatMessage {
    fn as_ref(&self) -> &ChatMessage {
        self
    }
}

/// A single tool invocation requested by the model.

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ToolCall {
    pub name: String,

    pub arguments: String,

    pub id: String,
}

impl AsRef<ToolCall> for ToolCall {
    fn as_ref(&self) -> &ToolCall {
        self
    }
}

/// Describes a tool the model may call. `input_schema` is the tool's JSON
/// schema serialized as a string (kept as a string to avoid modeling
/// arbitrary JSON Schema shapes in BAML).

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ToolDefinition {
    pub name: String,

    pub description: String,

    pub input_schema: String,
}

impl AsRef<ToolDefinition> for ToolDefinition {
    fn as_ref(&self) -> &ToolDefinition {
        self
    }
}
