// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Embedded BAML source files.

use std::collections::HashMap;
use std::sync::OnceLock;

static FILE_MAP: OnceLock<HashMap<String, String>> = OnceLock::new();

/// Get the embedded BAML source files.
pub fn get_baml_files() -> &'static HashMap<String, String> {
    FILE_MAP.get_or_init(|| {
        let mut m = HashMap::new();

        m.insert("generative_ui.baml".to_string(), "class UiNode {\n  tag \"rect\" | \"label\"\n  text string?\n  attrs map<string, string>\n  children UiNode[]\n}\n\nfunction GenerateUiTree(goal: string, state_json: string) -> UiNode {\n  client \"openai/gpt-4o-mini\"\n\n  prompt #\"\n    You are generating a UI description for a Freya (rsx!) desktop app.\n\n    Goal:\n    {{ goal }}\n\n    State (JSON):\n    {{ state_json }}\n\n    Rules:\n    - Return a UiNode tree.\n    - UiNode.tag MUST be either \\\"rect\\\" or \\\"label\\\".\n    - UiNode.text is only used when tag is \\\"label\\\".\n    - UiNode.attrs keys should be Freya-friendly layout attrs (examples: width, height, padding, background, direction, spacing).\n    - Colors should be rgb(r, g, b) strings when used.\n    - Keep the tree small (< 50 nodes).\n\n    {{ ctx.output_format }}\n  \"#\n}\n".to_string());

        m.insert("generators.baml".to_string(), "generator looprs_desktop_rust {\n  output_type rust\n  output_dir \"../src\"\n  version \"0.218.0\"\n  default_client_mode async\n  on_generate \"cargo fmt --manifest-path ../../Cargo.toml\"\n}\n".to_string());

        m
    })
}
