// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use super::*;
use crate::baml_client::types;
use baml::BamlDecode;

/// A single turn in a multi-turn conversation.

#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ChatMessage {
    pub role: Option<String>,

    pub content: Option<String>,
}

impl AsRef<ChatMessage> for ChatMessage {
    fn as_ref(&self) -> &ChatMessage {
        self
    }
}
