// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming union types.

use super::*;
use crate::baml_client::types;
use baml::BamlDecode;

/// Generated from: (string | Streaming.ToolCall[])
#[derive(Debug, Clone, BamlDecode)]
#[baml(union)]
pub enum Union2ListToolCallOrString {
    #[baml(name = "string")]
    String(String),

    #[baml(name = "List__ToolCall")]
    ListToolCall(Vec<ToolCall>),
}

impl AsRef<Union2ListToolCallOrString> for Union2ListToolCallOrString {
    fn as_ref(&self) -> &Union2ListToolCallOrString {
        self
    }
}

impl Default for Union2ListToolCallOrString {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
