// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use super::*;
use crate::baml_client::types;
use baml::BamlDecode;

#[derive(Debug, Clone, Default, BamlDecode)]

pub struct UiNode {
    pub tag: Option<types::Union2KlabelOrKrect>,

    pub text: Option<String>,

    pub attrs: std::collections::HashMap<String, String>,

    pub children: Vec<Box<UiNode>>,
}

impl AsRef<UiNode> for UiNode {
    fn as_ref(&self) -> &UiNode {
        self
    }
}
