// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod type_aliases;
mod unions;

pub use classes::*;
pub use type_aliases::*;
pub use unions::*;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone)]
pub enum StreamTypes {
    AdaptiveColors(AdaptiveColors),

    ContextAwareUiNode(ContextAwareUiNode),

    DataAnomaly(DataAnomaly),

    MaterialColors(MaterialColors),

    MessageAnalysis(MessageAnalysis),

    SentimentContext(SentimentContext),

    SentimentUiNode(SentimentUiNode),

    SystemHealth(SystemHealth),

    UiContext(UiContext),

    UiNode(UiNode),

    UserIntent(UserIntent),

    WorkflowState(WorkflowState),
}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            StreamTypes::AdaptiveColors(_) => "AdaptiveColors",

            StreamTypes::ContextAwareUiNode(_) => "ContextAwareUiNode",

            StreamTypes::DataAnomaly(_) => "DataAnomaly",

            StreamTypes::MaterialColors(_) => "MaterialColors",

            StreamTypes::MessageAnalysis(_) => "MessageAnalysis",

            StreamTypes::SentimentContext(_) => "SentimentContext",

            StreamTypes::SentimentUiNode(_) => "SentimentUiNode",

            StreamTypes::SystemHealth(_) => "SystemHealth",

            StreamTypes::UiContext(_) => "UiContext",

            StreamTypes::UiNode(_) => "UiNode",

            StreamTypes::UserIntent(_) => "UserIntent",

            StreamTypes::WorkflowState(_) => "WorkflowState",
        }
    }
}
