// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated union types.

use super::*;
use baml::{BamlDecode, BamlEncode};

/// Generated from: ("rect" | "label")
#[derive(Debug, Clone, BamlEncode, BamlDecode, PartialEq, Eq, Hash)]
#[baml(union)]
pub enum Union2KlabelOrKrect {
    #[baml(name = "string_rect", literal_string = "rect")]
    Krect,

    #[baml(name = "string_label", literal_string = "label")]
    Klabel,
}

impl AsRef<Union2KlabelOrKrect> for Union2KlabelOrKrect {
    fn as_ref(&self) -> &Union2KlabelOrKrect {
        self
    }
}

impl Default for Union2KlabelOrKrect {
    fn default() -> Self {
        Self::Krect
    }
}
