// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class builder wrappers for type-safe field access.

/// Wrapper for the `UiNode` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct UiNodeClassBuilder {
    inner: baml::ClassBuilder,
}

impl UiNodeClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner
            .as_type()
            .expect("UiNode is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `tag` field builder.
    pub fn property_tag(&self) -> baml::ClassPropertyBuilder {
        self.inner
            .get_property("tag")
            .expect("UiNode.tag is statically defined in .baml and should always be present")
    }

    /// Access the `text` field builder.
    pub fn property_text(&self) -> baml::ClassPropertyBuilder {
        self.inner
            .get_property("text")
            .expect("UiNode.text is statically defined in .baml and should always be present")
    }

    /// Access the `attrs` field builder.
    pub fn property_attrs(&self) -> baml::ClassPropertyBuilder {
        self.inner
            .get_property("attrs")
            .expect("UiNode.attrs is statically defined in .baml and should always be present")
    }

    /// Access the `children` field builder.
    pub fn property_children(&self) -> baml::ClassPropertyBuilder {
        self.inner
            .get_property("children")
            .expect("UiNode.children is statically defined in .baml and should always be present")
    }
}
