mod agent;
mod api;
pub mod approval;
pub mod bd;
mod config;
mod config_file;
pub mod context;
pub mod events;
pub mod hooks;
pub mod jj;
pub mod kan;
pub mod observation;
pub mod observation_manager;
pub mod providers;
mod tools;

pub use crate::agent::Agent;
pub use crate::approval::console_approval_prompt;
pub use crate::config::ApiConfig;
pub use crate::config_file::ProviderConfig;
pub use crate::context::SessionContext;
pub use crate::events::{Event, EventContext, EventManager};
pub use crate::hooks::{ApprovalCallback, Hook, HookExecutor, HookRegistry};
pub use crate::observation::Observation;
pub use crate::observation_manager::ObservationManager;
